### ISSUE TITLE
Issues broken

### ISSUE THREAD

**Issue by Inkata** [sciyoshi/redmine-slack#95] opened 2016-08-30 20:20 UTC
Hi!

After struggling to setup this plugin, all the issues on Redmine are broken. I've managed to have the settings come up in Admin -> plugins -> Redmine Slack -> Configure and It works.

If I select "post Issue Updates" on the config page, all issue editing breaks. When creating or editing any issue, I get an Internal Error page. I can Preview the issues, just when saving it fails.

If I deselect "post Issue updates" then no error is generated.

The box: 

<pre>
root@vm-one-205:~# ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
root@vm-one-205:~# which ruby -a
/usr/bin/ruby

root@vm-one-205:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

</pre>

and the error:

<pre>
NameError (undefined local variable or method `logger' for #<SlackListener:0x00000003b90958>):
  lib/plugins/redmine_slack/lib/redmine_slack/listener.rb:158:in `rescue in speak'
  lib/plugins/redmine_slack/lib/redmine_slack/listener.rb:152:in `speak'
  lib/plugins/redmine_slack/lib/redmine_slack/listener.rb:56:in `controller_issues_edit_after_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:488:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:475:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:180:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
</pre>

Where should I begin to debug?

Thanks!

**Comment by VitalyKrivoshapkin** [comment] 2016-08-31 01:29
Check Redmine version
Plugin compatible with:	Redmine 3.1.x, 3.0.x, 2.6.x, 2.5.x, 2.4.x, 2.3.x, 2.2.x, 2.1.x, 2.0.x

**Comment by sciyoshi** [comment] 2016-11-08 04:06
Thanks @VitalyKrivoshapkin, this sounds like a duplicate of #97.

**Closed by sciyoshi** 2016-11-08 04:06 UTC
