### ISSUE TITLE
This plugin seems to break my Redmine instance

### ISSUE THREAD

**Issue by byrongibby** [sciyoshi/redmine-slack#142] opened 2018-11-12 09:47 UTC
After installing the plugin, I try to restart the Apache (+ Passenger) server and I get the following error (copied from the Apache error_log):

 ```
App 28635 output:     /home/redmine/redmine/plugins/redmine_slack/init.rb:26:in `<top (required)>'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
App 28635 output:     /home/redmine/redmine/lib/redmine/plugin.rb:156:in `block in load'
App 28635 output:     /home/redmine/redmine/lib/redmine/plugin.rb:147:in `each'
App 28635 output:     /home/redmine/redmine/lib/redmine/plugin.rb:147:in `load'
App 28635 output:     /home/redmine/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:613:in `each'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `each'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:415:in `call'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
App 28635 output:     /home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
App 28635 output:     config.ru:3:in `require'
App 28635 output:     config.ru:3:in `block in <main>'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
App 28635 output:     config.ru:1:in `new'
App 28635 output:     config.ru:1:in `<main>'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.5/src/helper-scripts/rack-loader.rb:96:in `eval'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.5/src/helper-scripts/rack-loader.rb:96:in `load_app'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.5/src/helper-scripts/rack-loader.rb:116:in `block in <module:App>'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.5/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.5/src/helper-scripts/rack-loader.rb:115:in `<module:App>'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.5/src/helper-scripts/rack-loader.rb:28:in `<module:PhusionPassenger>'
App 28635 output:     /home/redmine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.5/src/helper-scripts/rack-loader.rb:27:in `<main>'
[ E 2018-11-12 11:08:29.2589 28275/To age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/redmine/redmine: The application encountered the following error: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param (NoMethodError)
  Error ID: 5bf7f0bc
  Error details saved to: /tmp/passenger-error-WROEKj.html

[ E 2018-11-12 11:08:29.2620 28275/T7 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-2] Cannot checkout session because a spawning error occurred. The identifier of the error is 5bf7f0bc. Please see earlier logs for details about the error.
[ E 2018-11-12 11:08:48.1288 28275/T5 age/Cor/SecurityUpdateChecker.h:505 ]: Security update check failed: Couldn't connect to server for https://securitycheck.phusionpassenger.com/v1/check.json (if this error persists check your connection security or try upgrading Passenger) (next check in 24 hours)
```

Not sure if I am just doing something stupid, but I followed the installation intsructions as in the README. If I remove the plugin the problem goes away.

My Redmine info:

```
Environment:
  Redmine version                3.4.6.devel
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux]
  Rails version                  5.2.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  no plugin installed
```

**Comment by veracosta** [comment] 2018-11-20 08:03
I'm not sure what the exact cause, but it look like your environment is not suited for Redmine 3.4.

Check the link below.
http://www.redmine.org/projects/redmine/wiki/redmineinstall

Redmine 3.4 does not support ruby 2.5.

**Comment by veracosta** [comment] 2018-11-20 08:10
https://stackoverflow.com/questions/41154337/rails-5-deprecation-warning-to-prepare-is-deprecated

Your error_log says `to_prepare` method is undefined, and according to the link above, it seems that `to_prepare` is deprecated and was removed from Rails 5.1.

As I mentioned previously, perhaps your problem is being caused by software version.

**Comment by sciyoshi** [comment] 2019-01-30 16:42
Closing the issue for now, but please reopen if you continue to experience this. Thank you @veracosta for helping to debug!

**Closed by sciyoshi** 2019-01-30 16:42 UTC
