### ISSUE TITLE
Notifications are not send

### ISSUE THREAD

**Issue by prodigy7** [sciyoshi/redmine-slack#107] opened 2016-11-09 10:23 UTC
I follwed the instructions and installed the plugin. So far, everything is fine and I configure the plugin, also the httpclient is installed. But when I edit a wiki entry or add something to a issue, nothing happens in slack. I've also tried it with the curl instructions suggested by slack and this sample works (send something to channel). When I leave the channel field empty, an error occours what indicates me, that the plugin are called.

What could be wrong?

  Redmine version                3.3.1.stable.15949
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.7.1

**Comment by kiecoorp** [comment] 2016-11-16 13:14
I also have the problem : 

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_slack                  0.2

**Comment by antidrugue** [comment] 2016-11-27 04:02
Same issue here, since upgrading to **Redmine 3.3.1**. Everything was working fine in **Redmine 3.2.4**.

~~~~
  Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_slack                  0.2
~~~~

**Comment by cerw** [comment] 2016-12-05 06:55
Same here.

**Comment by sciyoshi** [comment] 2016-12-05 16:23
Thank you all for the detailed bug report. I'll take a look if I can reproduce the issue and get a fix.

**Comment by sciyoshi** [comment] 2016-12-05 16:34
Can you try running from the latest version of master? There was a possible regression introduced with a recent commit that might have caused the problems you are seeing.

**Comment by NerdsvilleCEO** [comment] 2016-12-13 02:57
I am having this same issue

**Comment by NerdsvilleCEO** [comment] 2016-12-13 02:58
Nevermind, I resolved it by changing the username

**Comment by liukun5** [comment] 2016-12-16 05:39
@NerdsvilleCEO  how resolve it by changing the username?

**Comment by kacchan822** [comment] 2017-07-12 07:37
I also have the problem:
```
Environment:
  Redmine version                3.4.1.stable
  Ruby version                   2.4.0-p0 (2016-12-24) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_glanceyear             0.0.1
  redmine_slack                  0.2
  sidebar_hide                   0.0.8
```

and I tried to fix it. 
I found `Setting.plugin_redmine_slack[:post_updates] ` returns NillClass.
`Setting.plugin_redmine_slack[:icon]`
`Setting.plugin_redmine_slack[:slack_url]`
`Setting.plugin_redmine_slack[:channel]` ... these also returns NillClass.

So, I changed codes as below... and restarted Unicorn.
Notifications are send to SLACK!.

```diff
diff --git a/lib/redmine_slack/listener.rb b/lib/redmine_slack/listener.rb
index aa062a0..f8f17b2 100644
--- a/lib/redmine_slack/listener.rb
+++ b/lib/redmine_slack/listener.rb
@@ -1,5 +1,6 @@
 require 'httpclient'
 
+
 class SlackListener < Redmine::Hook::Listener
        def controller_issues_new_after_save(context={})
                issue = context[:issue]
@@ -32,7 +33,7 @@ class SlackListener < Redmine::Hook::Listener
                        :title => I18n.t("field_watcher"),
                        :value => escape(issue.watcher_users.join(', ')),
                        :short => true
-               } if Setting.plugin_redmine_slack[:display_watchers] == 'yes'
+               } if Setting.plugin_redmine_slack['display_watchers'] == 'yes'
 
                speak msg, channel, attachment, url
        end
@@ -44,7 +45,7 @@ class SlackListener < Redmine::Hook::Listener
                channel = channel_for_project issue.project
                url = url_for_project issue.project
 
-               return unless channel and url and Setting.plugin_redmine_slack[:post_updates] == '1'
+               return unless channel and url and Setting.plugin_redmine_slack['post_updates'] == '1'
                return if issue.is_private?
                return if journal.private_notes?
 
@@ -105,7 +106,7 @@ class SlackListener < Redmine::Hook::Listener
        end
 
        def controller_wiki_edit_after_save(context = { })
-               return unless Setting.plugin_redmine_slack[:post_wiki_updates] == '1'
+               return unless Setting.plugin_redmine_slack['post_wiki_updates'] == '1'
 
                project = context[:project]
                page = context[:page]
@@ -128,9 +129,9 @@ class SlackListener < Redmine::Hook::Listener
        end
 
        def speak(msg, channel, attachment=nil, url=nil)
-               url = Setting.plugin_redmine_slack[:slack_url] if not url
-               username = Setting.plugin_redmine_slack[:username]
-               icon = Setting.plugin_redmine_slack[:icon]
+               url = Setting.plugin_redmine_slack['slack_url'] if not url
+               username = Setting.plugin_redmine_slack['username']
+               icon = Setting.plugin_redmine_slack['icon']
 
                params = {
                        :text => msg,
@@ -191,7 +192,7 @@ private
                return [
                        (proj.custom_value_for(cf).value rescue nil),
                        (url_for_project proj.parent),
-                       Setting.plugin_redmine_slack[:slack_url],
+                       Setting.plugin_redmine_slack['slack_url'],
                ].find{|v| v.present?}
        end
 
@@ -203,7 +204,7 @@ private
                val = [
                        (proj.custom_value_for(cf).value rescue nil),
                        (channel_for_project proj.parent),
-                       Setting.plugin_redmine_slack[:channel],
+                       Setting.plugin_redmine_slack['channel'],
                ].find{|v| v.present?}
 
                # Channel name '-' is reserved for NOT notifying
```

I'm not good at ruby and rails... Why did fix the problem...

**Comment by sciyoshi** [comment] 2017-08-03 20:38
Should be fixed by https://github.com/sciyoshi/redmine-slack/pull/121 - thank you for the report!

**Closed by sciyoshi** 2017-08-03 20:38 UTC
Labels: bug
