### ISSUE TITLE
(Not an issue maybe a request ;-) Not Working under a proxy environment

### ISSUE THREAD

**Issue by carcuevas** [sciyoshi/redmine-slack#114] opened 2017-03-20 15:56 UTC
Hi,

it seems that whenever a redmine environment has to communicate to SLACK using a proxy, it seems to don't work: 

I am setting the proxy as ENV at the beginning in the redmine_slack/lib/redmine_slack/listener.rb for the HTTPClient 
`
ENV['http_proxy'] = 'http://proxyURL:proxyPORT'`

Also I tried using 
`client = HTTPClient.new('http://proxyURL:proxyPORT')`

But somehow it seems that the variables are taken into consideration but no message is sent .....  It's kind of weird... Am I doing something wrong with this??

Thanks very much in advance for the help :)

**Comment by sciyoshi** [comment] 2017-12-20 23:42
Thank you @carcuevas, this is a duplicate of issue #94.

**Closed by sciyoshi** 2017-12-20 23:42 UTC
