### ISSUE TITLE
Send messages async

### ISSUE THREAD

**Issue by Slind14** [sciyoshi/redmine-slack#49] opened 2015-07-01 16:26 UTC
Hey,

since I added redmine-slack all ticket creations and edits went super slow. Once I remove the plugin it is normal again. Would it be possible to implement it async. This also wouldn't break the service when slack is down/the connection to slack is failing.

**Comment by sciyoshi** [comment] 2015-07-03 14:49
@Slind14 - thanks for the report. Totally open to doing this, just haven't had the bandwidth. This is also a duplicate of #39. PRs welcome!

**Closed by sciyoshi** 2015-07-03 14:49 UTC

**Comment by Slind14** [comment] 2015-07-03 17:59
ahh I was looking for async, background.. but not additional thread :)
